name: alto
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - cuda-toolkit=12.1
  - torchvision
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - jupyterlab
  - mypy>=1.10
  - tqdm>=4.66.2
  - types-tqdm
  - ray-default>=2.12
  - ujson
  - types-ujson
  - loguru
  - msgpack-python
  - msgspec
  - portalocker
  - cloudpickle
  - gcc
  - gxx
  - cmake
  - faiss-gpu
  - gitpython
  - bitarray
  - ninja
  - spacy
  - python-dotenv
  - grpcio
  - grpcio-tools
  - types-protobuf
  - tiktoken
  - bottleneck
  - nltk
  - flask
  - numba
  - intel-cmplr-lib-rt
  - pip:
    - transformers
    - datasets
    - vllm
